### ISSUE TITLE
Drop-in replacement

### ISSUE THREAD

**Issue by amk221** [stefanpenner/ember-improved-cp#5]
Currently, this isn't a drop in replacement (doing a find and replace for `ember-computed` with `ember-improved-cp/read-only`)
...because `alias` and `reads` aren't available.

Would be good if this package exported all of Ember's [built-in](http://emberjs.com/api/classes/Ember.computed.html#index) CPs.

**Comment by stefanpenner** [comment]
> ...because alias and reads aren't available.

I would gladly discuss this further.

The reason they are not yet included, is that `reads` and `alias` really tend to want to be expressed as `readOnly`. If one is already accomplishing this via search/replace, my assumption that `reads` and `alias` would also be simple to search/replace. Hence being omitted from this library.

thoughts?

**Comment by amk221** [comment]
>  reads and alias really tend to want to be expressed as readOnly

..in that case, surely they'd be perfect to be set as readonly by default by using this repo, no?

``` javascript
import { alias } from 'ember-computed';
import { findBy } from 'ember-improved-cp/readonly'

export default Component.extend({
  thing:  alias('session.thing.firstObject').readOnly(),  // y no improved?
  things: findBy('session.things', 'foo'),                // yay improved
  actions: {
    selectThing(thing) {
      this.set('thing', thing); // uh oh
    } 
  } 
});
```

...I honestly don't mind now I've got it all set up though...

**Comment by stefanpenner** [comment]
> thing:  alias('session.thing.firstObject').readOnly(),  // y no improved?

because that is the same as saying: `thing: readOnly('session.thing.firstObject')`

That being said, it may be appropriate to:
- include reads and alias
- deprecate them, to guide users to `readOnly` for those use-cases

thoughts?

**Comment by amk221** [comment]
Roger!
