### ISSUE TITLE
Prevent usage of ember-computed

### ISSUE THREAD

**Issue by amk221** [stefanpenner/ember-improved-cp#6]
Do you have any recommendations for preventing usage of...

```javascript
import computed from 'ember-computed';
```

...to makes sure...

```javascript
import computed from 'ember-improved-cp/read-only';
```

...is always use instead?

Perhaps it could warn or something. Or it may be possible with eslint?

**Comment by amk221** [comment]
In fact, I think http://eslint.org/docs/rules/no-restricted-imports might be what I need. 

It might be worth [mentioning in the readme](https://github.com/amk221/ember-improved-cp/commit/a7988acfb1a62be5505a738f83dc5c918235ab5e)? Because in large teams it's easy for `ember-computed`to creep back in again after an initial find and replace with `ember-improved-cp/read-only`

_Edit:_
```javascript
// .eslintrc.js
'no-restricted-imports': ['error', {
  paths: ["ember-computed"]
}]
```

**Comment by stefanpenner** [comment]
hmm, my first thought is that this may be better suited for a linter? Although we may be able  do something funky here, to cause usage of `ember-computed` to warn... but that feels kinda dirty.

**Comment by amk221** [comment]
Its ok, the linting solution works well. And to be honest, you might want to still use `ember-computed` for things like:

```javascript
foo: computed({
  set() {...},
  get() {...}
})
```
