### ISSUE TITLE
Deprecation warning when building ember app with ember-improved-cp

### ISSUE THREAD

**Issue by mikerhyssm** [stefanpenner/ember-improved-cp#7]
`DEPRECATION: An addon is trying to access project.nodeModulesPath. This is not a reliable way to discover npm modules. Instead, consider doing: require("resolve").sync(something, { basedir: project.root }). Accessed from:   DependencyVersionChecker.NPMDependencyVersionChecker (/node_modules/ember-improved-cp/node_modules/ember-cli-version-checker/src/npm-dependency-version-checker.js:11:32)`

Is logged when building an app with ember-improved-cp installed, it seems that this can be fixed by updating ember-cli-babel which depends on: https://github.com/ember-cli/ember-cli-version-checker/issues/48

**Comment by stefanpenner** [comment]
I'll go an update all the deps and stuff. Thanks for point this out!

**Comment by stefanpenner** [comment]
fix should be released as v2.0.0 🎉

**Comment by stefanpenner** [comment]
let me know if that doesn't take care of your issue

**Comment by mikerhyssm** [comment]
All sorted ! Thanks for the quick turnaround 😃
